spring.application.name=clean-architecture25

server.port=8005

# Database setting
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;database=clean_architecture;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=Allrole123!

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Handle naming conventions table db (Snake Case to Camel Case)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Enable feature virtual thread
spring.threads.virtual.enabled=true

# HikariCP Settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000

# Not Use
#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:scripts/sql/01_schema.sql